db.driverClassName=org.postgresql.Driver
# ================================================== SERVER
#db.jdbcUrl=jdbc:log4jdbc:postgresql://192.168.0.190:5432/optimizer_dev
#db.username=wellconn
#db.password=dbdnpfzjs1!
# ================================================== LOCAL
db.jdbcUrl=jdbc:log4jdbc:postgresql://211.168.199.244:5432/optimizer
db.username=wellconn
db.password=dbdnpfzjs1!
# [excel]
excel.upload = excel/sample.xlsx
# ==================================================
db.dataSource.cachePrepStmts=true
db.dataSource.prepStmtCacheSize=250
db.dataSource.prepStmtCacheSqlLimit=2048
syncUrl = http://192.168.0.194:8180/OPTIMIZERAPI/syncPolicy.do
server.servlet.context-path=/
spring.main.banner-mode=off
logging.level.root=INFO